# api-compose.yml tells Docker how to run that image

services:
  the_news_hub_api:
    build:
        context: ..
        dockerfile: api/Dockerfile
    ports:
      - "7010:7010"
    container_name: the-news-hub-api
    env_file:
      - ../.env
    restart: unless-stopped
    volumes:
      - ./api:/app
networks:
  db_default:
    external: true